#Hugo configuration
title = "asdf"
baseURL = "https:\/\/www.asdfsadf.123commmm"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "asdfsadf.123commmm"
